service: mindbody-scraper
provider:
  name: aws
  profile: banjo
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    region: ${self:provider.region}
    stage: ${self:provider.stage}
    natOff: https://s3-us-west-2.amazonaws.com/mindbody-scraper-auth/mindbody-scraper-auth-off-template.yml
    natOn: https://s3-us-west-2.amazonaws.com/mindbody-scraper-auth/mindbody-scraper-auth-on-template.yml
    scraperLogName:
      Ref: scraperLog
    scraperQueueUrl:
      Ref: scraperQueue
    authStackName:
      Fn::GetAtt: [ authStack, Outputs.StackName ]
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - Fn::GetAtt: [ appointmentTypesTable, Arn ]
        - Fn::GetAtt: [ classEventsTable, Arn ]
        - Fn::GetAtt: [ classCategoriesTable, Arn ]
        - Fn::GetAtt: [ classTypesTable, Arn ]
        - Fn::GetAtt: [ clientsTable, Arn ]
        - Fn::GetAtt: [ pricingDetailsTable, Arn ]
        - Fn::GetAtt: [ productsTable, Arn ]
        - Fn::GetAtt: [ staffTable, Arn ]
    - Effect: Allow
      Action:
        - logs:*
        - ssm:*
        - s3:*
        - ec2:*
        - cloudformation:*
        - lambda:*
        - sqs:*
      Resource:
        - "*"

custom:
  vpc:
    securityGroupIds:
      - Fn::GetAtt: [ authStack, Outputs.SecurityGroupId ]
    subnetIds:
      - Fn::GetAtt: [ authStack, Outputs.PrivateSubnetId ]

functions:
  clearLogs:
    handler: functions/clearLogs.handler
  getStudio:
    handler: functions/getStudio.handler
  getTest:
    handler: functions/getTest.handler
    vpc: ${self:custom.vpc}
  mbFetch:
    handler: functions/mbFetch.handler
    timeout: 90
    reservedConcurrency: 8
    vpc: ${self:custom.vpc}
  getToken:
    handler: functions/getToken.handler
    timeout: 90
    reservedConcurrency: 2
    vpc: ${self:custom.vpc}
  processQueue:
    handler: functions/processQueue.handler
    timeout: 90
    reservedConcurrency: 4
    events:
      - sqs:
          batchSize: 4
          arn:
            Fn::GetAtt: [ scraperQueue, Arn ]
  createAuthVpc:
    handler: functions/createAuthVpc.handler
  deleteAuthVpc:
    handler: functions/deleteAuthVpc.handler
  getBusinessLocations:
    handler: functions/getBusinessLocations.handler
    timeout: 90
  getResources:
    handler: functions/getResources.handler
    timeout: 90
  getProductsByLetter:
    handler: functions/getProductsByLetter.handler
    timeout: 90
  getProductsByVariantId:
    handler: functions/getProductsByVariantId.handler
    timeout: 90
  getProductDetails:
    handler: functions/getProductDetails.handler
    timeout: 90
  getProducts:
    handler: functions/getProducts.handler
    timeout: 90
  getAppointmentTypes:
    handler: functions/getAppointmentTypes.handler
    timeout: 90
  getPricingDetails:
    handler: functions/getPricingDetails.handler
    timeout: 90
  getPricing:
    handler: functions/getPricing.handler
    timeout: 90
  getClassTypeDetails:
    handler: functions/getClassTypeDetails.handler
    timeout: 90
  getClassTypeEvents:
    handler: functions/getClassTypeEvents.handler
    timeout: 90
  getClassTypeEventsTeachers:
    handler: functions/getClassTypeEventsTeachers.handler
    timeout: 90
  getClassTypes:
    handler: functions/getClassTypes.handler
    timeout: 90
  getStaff:
    handler: functions/getStaff.handler
    timeout: 90
  getStaffMember:
    handler: functions/getStaffMember.handler
    timeout: 90
  getUserProfile:
    handler: functions/getUserProfile.handler
    timeout: 90
  getUsers:
    handler: functions/getUsers.handler
    timeout: 90
  getDateRange:
    handler: functions/getDateRange.handler
    timeout: 90
  getClassEvents:
    handler: functions/getClassEvents.handler
    timeout: 90
  getClassEventUsers:
    handler: functions/getClassEventUsers.handler
    timeout: 90
resources:
  Resources:
    scraperQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "ScraperQueue"
        ReceiveMessageWaitTimeSeconds: 10
        VisibilityTimeout: 90
    authStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: ${self:provider.environment.natOn}
    scraperLog:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 7
    appointmentTypesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AppointmentTypesTable
        AttributeDefinitions:
          - AttributeName: appointmentTypeId
            AttributeType: S
        KeySchema:
          - AttributeName: appointmentTypeId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    classEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClassEventsTable
        AttributeDefinitions:
          - AttributeName: classId
            AttributeType: S
        KeySchema:
          - AttributeName: classId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    classCategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClassCategoriesTable
        AttributeDefinitions:
          - AttributeName: classCategoryId
            AttributeType: S
        KeySchema:
          - AttributeName: classCategoryId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    classTypesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClassTypesTable
        AttributeDefinitions:
          - AttributeName: classTypeId
            AttributeType: S
        KeySchema:
          - AttributeName: classTypeId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    clientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientsTable
        AttributeDefinitions:
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: clientId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '5'
          WriteCapacityUnits: '5'
    staffTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StaffTable
        AttributeDefinitions:
          - AttributeName: staffMemberId
            AttributeType: S
        KeySchema:
          - AttributeName: staffMemberId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    pricingDetailsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PricingDetailsTable
        AttributeDefinitions:
          - AttributeName: pricingDetailId
            AttributeType: S
        KeySchema:
          - AttributeName: pricingDetailId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
