service: mindbody-scraper
provider:
  name: aws
  profile: banjo
  runtime: nodejs8.10
  region: us-west-2
  environment:
    classEventQueueUrl:
      "Ref": classEventQueue
    classEventUserQueueUrl:
      "Ref": classEventUserQueue
    clientQueueUrl:
      "Ref": clientQueue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "${self:resources.Outputs.ClassEventsTable.Value}"
        - "${self:resources.Outputs.ClientsTable.Value}"
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - "*"

functions:
  getClassTypes:
    handler: functions/getClassTypes.handler
  getUserProfile:
    handler: functions/getUserProfile.handler
    timeout: 120
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt: [ clientQueue, Arn ]
  getUsers:
    handler: functions/getUsers.handler
    timeout: 120
  getDateRange:
    handler: functions/getDateRange.handler
  getClassEvents:
    handler: functions/getClassEvents.handler
    timeout: 120
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt: [ classEventQueue, Arn ]
  getClassEventUsers:
    handler: functions/getClassEventUsers.handler
    timeout: 120
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt: [ classEventUserQueue, Arn ]
resources:
  Resources:
    classEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClassEventsTable
        AttributeDefinitions:
          - AttributeName: classId
            AttributeType: S
        KeySchema:
          - AttributeName: classId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    clientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientsTable
        AttributeDefinitions:
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: clientId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    classEventQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "ClassEventQueue"
        VisibilityTimeout: 120
    classEventUserQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "ClassEventUserQueue"
        VisibilityTimeout: 120
    clientQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "ClientQueue"
        VisibilityTimeout: 120
  Outputs:
    ClassEventsTable:
      Description: The ARN for the Class Events Table
      Value:
        "Fn::GetAtt": [ classEventsTable, Arn ]
    ClientsTable:
      Description: The ARN for the Clients Table
      Value:
        "Fn::GetAtt": [ clientsTable, Arn ]
