service: mindbody-scraper
provider:
  name: aws
  profile: banjo
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    region: ${self:provider.region}
    stage: ${self:provider.stage}
    allocationId:
      Fn::GetAtt: [ EIP, AllocationId ]
    routeTableId:
      Ref: PrivateRouteTable
    subnetId:
      Ref: PublicSubnetA
    vpcId:
      Ref: VPC
    scraperQueueUrl:
      Ref: scraperQueue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - Fn::GetAtt: [ appointmentTypesTable, Arn ]
        - Fn::GetAtt: [ classEventsTable, Arn ]
        - Fn::GetAtt: [ classCategoriesTable, Arn ]
        - Fn::GetAtt: [ classTypesTable, Arn ]
        - Fn::GetAtt: [ clientsTable, Arn ]
        - Fn::GetAtt: [ pricingDetailsTable, Arn ]
        - Fn::GetAtt: [ productsTable, Arn ]
    - Effect: Allow
      Action:
        - ec2:*
        - lambda:*
        - sqs:*
      Resource:
        - "*"
custom:
  natVPC:
    securityGroupIds:
      - Ref: SecurityGroup
    subnetIds:
      - Ref: PrivateSubnet

functions:
  processQueue:
    handler: functions/processQueue.handler
    timeout: 120
    reservedConcurrency: 6
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt: [ scraperQueue, Arn ]
  mbFetch:
    handler: functions/mbFetch.handler
    timeout: 120
    vpc: ${self:custom.natVPC}
  getToken:
    handler: functions/getToken.handler
    timeout: 120
    reservedConcurrency: 2
    vpc: ${self:custom.natVPC}
  createNat:
    handler: functions/createNat.handler
    timeout: 600
  deleteNat:
    handler: functions/deleteNat.handler
    timeout: 600
  getTest:
    handler: functions/getTest.handler
    timeout: 30
  getProductsByLetter:
    handler: functions/getProductsByLetter.handler
    timeout: 120
  getProductsByVariantId:
    handler: functions/getProductsByVariantId.handler
    timeout: 120
  getProductDetails:
    handler: functions/getProductDetails.handler
    timeout: 120
  getProducts:
    handler: functions/getProducts.handler
    timeout: 120
  getAppointmentTypes:
    handler: functions/getAppointmentTypes.handler
    timeout: 120
  getPricingDetails:
    handler: functions/getPricingDetails.handler
    timeout: 120
  getPricing:
    handler: functions/getPricing.handler
    timeout: 120
  getClassTypeDetails:
    handler: functions/getClassTypeDetails.handler
    timeout: 120
  getClassTypes:
    handler: functions/getClassTypes.handler
    timeout: 120
  getUserProfile:
    handler: functions/getUserProfile.handler
    timeout: 120
  getUsers:
    handler: functions/getUsers.handler
    timeout: 120
  getDateRange:
    handler: functions/getDateRange.handler
    timeout: 120
  getClassEvents:
    handler: functions/getClassEvents.handler
    timeout: 120
  getClassEventUsers:
    handler: functions/getClassEventUsers.handler
    timeout: 120
resources:
  Resources:
    scraperQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "ScraperQueue"
        VisibilityTimeout: 20
    appointmentTypesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AppointmentTypesTable
        AttributeDefinitions:
          - AttributeName: appointmentTypeId
            AttributeType: S
        KeySchema:
          - AttributeName: appointmentTypeId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    classEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClassEventsTable
        AttributeDefinitions:
          - AttributeName: classId
            AttributeType: S
        KeySchema:
          - AttributeName: classId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    classCategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClassCategoriesTable
        AttributeDefinitions:
          - AttributeName: classCategoryId
            AttributeType: S
        KeySchema:
          - AttributeName: classCategoryId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    classTypesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClassTypesTable
        AttributeDefinitions:
          - AttributeName: classTypeId
            AttributeType: S
        KeySchema:
          - AttributeName: classTypeId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    clientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientsTable
        AttributeDefinitions:
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: clientId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    pricingDetailsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PricingDetailsTable
        AttributeDefinitions:
          - AttributeName: pricingDetailId
            AttributeType: S
        KeySchema:
          - AttributeName: pricingDetailId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '2'
          WriteCapacityUnits: '2'

# VPC Resources
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        InstanceTenancy: default
    InternetGateway:
      Type: AWS::EC2::InternetGateway
    VPCGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
          VpcId:
            Ref: VPC
          InternetGatewayId:
            Ref: InternetGateway
    PublicSubnetA:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-west-2a
        VpcId:
          Ref: VPC
        CidrBlock: 10.0.1.0/24
        MapPublicIpOnLaunch: true
    RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: VPC
    InternetRoute:
      Type: AWS::EC2::Route
      DependsOn: VPCGatewayAttachment
      Properties:
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: InternetGateway
        RouteTableId:
          Ref: RouteTable
    PublicSubnetARouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          Ref: RouteTable
        SubnetId:
          Ref: PublicSubnetA
    PrivateSubnet:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-west-2a
        VpcId:
          Ref: VPC
        CidrBlock: 10.0.4.0/24
        MapPublicIpOnLaunch: false
    PrivateRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: VPC
    EIP:
      Type: AWS::EC2::EIP
      Properties:
        Domain: vpc
    PrivateSubnetRouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          Ref: PrivateRouteTable
        SubnetId:
          Ref: PrivateSubnet
    SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: "mindbody scraper SG"
        GroupDescription: "Mind body scraper security group"
        VpcId:
          Ref: VPC
    SecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupId:
          Ref: SecurityGroup
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        SourceSecurityGroupId:
          Ref: SecurityGroup
